id: P75393335
initial_creation_type: input
source_metadata:
  title: Auspiciousness Series
  language: zh
  description: 'A selection of texts on the theme of auspiciousness (maṅgalam; bkra
    shis) including verses of auspiciousness (maṅgalagāthā) and prayers:'
  volume:
    185dc5611c1b453e81cf999d86cafb66:
      title: A Prayer for Auspiciousness
      parent: Verses of Auspiciousness
    fbdf94b2f2654741b881111f376ffd6b:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Verses of Auspiciousness
    5350a73efe0d4aec9310622def5aff23:
      title: Verses of Auspiciousness
      parent: Verses of Auspiciousness
    4380915632de4d02a0ed99edbada1085:
      title: 'Virtuous Adornment for All the World: Verses to Bring Auspiciousness
        and Wellbeing'
      parent: Verses of Auspiciousness
    5d6092c08e85468788d8467fe1b72cda:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Verses of Auspiciousness
created_at: '2022-03-01T02:52:02.801608'
last_modified_at: '2022-03-01T02:52:02.801610'
